# Generated by Django 4.2.7 on 2023-11-08 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('disponibilidade', models.BooleanField()),
                ('preco', models.FloatField()),
                ('hospede', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.usuario')),
            ],
        ),
    ]
