# Generated by Django 4.2.7 on 2023-11-08 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_diaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaria',
            name='hospede',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.usuario'),
        ),
    ]
